export const MAX_WORKSPACE_NODES = 64;
export const MAX_EXPRESSION_LENGTH = 64;
export const MAX_ABSOLUTE_INPUT_VALUE = 100;

export const MIN_MATRIX_DURATION_MS = 100;
export const MAX_MATRIX_DURATION_MS = 3_000;
export const MAX_SESSION_ELAPSED_MS =
	MAX_WORKSPACE_NODES * MAX_MATRIX_DURATION_MS * 2;
